############################################################################
# Copyright 2007-2026 Universidade do Porto - Faculdade de Engenharia      #
# Laboratório de Sistemas e Tecnologia Subaquática (LSTS)                  #
############################################################################
# This file is part of DUNE: Unified Navigation Environment.               #
#                                                                          #
# Commercial Licence Usage                                                 #
# Licencees holding valid commercial DUNE licences may use this file in    #
# accordance with the commercial licence agreement provided with the       #
# Software or, alternatively, in accordance with the terms contained in a  #
# written agreement between you and Faculdade de Engenharia da             #
# Universidade do Porto. For licensing terms, conditions, and further      #
# information contact lsts@fe.up.pt.                                       #
#                                                                          #
# Modified European Union Public Licence - EUPL v.1.1 Usage                #
# Alternatively, this file may be used under the terms of the Modified     #
# EUPL, Version 1.1 only (the "Licence"), appearing in the file LICENCE.md #
# included in the packaging of this file. You may not use this work        #
# except in compliance with the Licence. Unless required by applicable     #
# law or agreed to in writing, software distributed under the Licence is   #
# distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF     #
# ANY KIND, either express or implied. See the Licence for the specific    #
# language governing permissions and limitations at                        #
# https://github.com/LSTS/dune/blob/master/LICENCE.md and                  #
# http://ec.europa.eu/idabc/eupl.html.                                     #
############################################################################
# Author: João Bogas                                                       #
############################################################################
# Navigation Simulation Replay                                             #
############################################################################

[Require common/imc-addresses.ini]

[Require auv/transports.ini]
[Require auv/navigation.ini]
[Require auv/general.ini]


[General]
Vehicle                                     = lauv-simulator-1
Vehicle Type                                = lauv
Absolute Maximum Depth                      = 100


# lauv-xplore-3 navigation parameters
[Navigation.AUV.Navigation]
GPS Maximum HACC                            = 40.0
Distance Between LBL and GPS                = 0.98
Abort if Uncertainty Exceeded               = false
Activate speed to rpm estimation limit      = true
Depth sensor localization in x axis         = 0.92
Rpm to speed estimation                     = true
speed to rpm estimation percentage limit    = 15


[Simulators.Velocity]
Enabled                                     = Always
Entity Label                                = Velocity Simulator
File path                                   = ${VELOCITY_CSV}

[Transports.UDP]
Ignore Filter                               = true

[Transports.Replay]
Enabled                                     = Always
Entity Label                                = Replay
Time Multiplier                             = 1.0
Seconds to skip                             = 0.0
Entities                                    = Depth Sensor,
                                              AHRS,
                                              Attitude,
                                              Obstacle Monitor,
                                              Echo Sounder,
                                              IMU,
                                              GPS

Replay Messages                             = AngularVelocity,
                                              Acceleration,
                                              Distance,
                                              Depth,
                                              DesiredPath,
                                              DesiredZ,
                                              DevCalibrationControl,
                                              Distance,
                                              EntityState,
                                              EntityActivationState,
                                              EulerAngles,
                                              EulerAnglesDelta,
                                              GpsFix,
                                              MagneticField,
                                              OperationalLimits,
                                              PlanSpecification,
                                              Rpm,
                                              VehicleMedium,
                                              EstimatedState,
                                              WaterVelocity

Load At Start                               = ${LOAD_AT_START}
