############################################################################
# Copyright 2007-2026 Universidade do Porto - Faculdade de Engenharia      #
# Laboratório de Sistemas e Tecnologia Subaquática (LSTS)                  #
############################################################################
# This file is part of DUNE: Unified Navigation Environment.               #
#                                                                          #
# Commercial Licence Usage                                                 #
# Licencees holding valid commercial DUNE licences may use this file in    #
# accordance with the commercial licence agreement provided with the       #
# Software or, alternatively, in accordance with the terms contained in a  #
# written agreement between you and Faculdade de Engenharia da             #
# Universidade do Porto. For licensing terms, conditions, and further      #
# information contact lsts@fe.up.pt.                                       #
#                                                                          #
# Modified European Union Public Licence - EUPL v.1.1 Usage                #
# Alternatively, this file may be used under the terms of the Modified     #
# EUPL, Version 1.1 only (the "Licence"), appearing in the file LICENCE.md #
# included in the packaging of this file. You may not use this work        #
# except in compliance with the Licence. Unless required by applicable     #
# law or agreed to in writing, software distributed under the Licence is   #
# distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF     #
# ANY KIND, either express or implied. See the Licence for the specific    #
# language governing permissions and limitations at                        #
# https://github.com/LSTS/dune/blob/master/LICENCE.md and                  #
# http://ec.europa.eu/idabc/eupl.html.                                     #
############################################################################
# Author: Jose Pinto                                                       #
############################################################################
# LAUV Xplore 1 SOI-specific simulation                                    #
############################################################################

[Require lauv-xplore-1.ini]

[Require common/drip.ini]

[Control.Path.PurePursuit]
Along-track -- Monitor      = False

[Simulators.VSIM]
Enabled                     = Simulation
Time Multiplier             = 60.0

[Simulators.Iridium]
Enabled                     = Never
Entity Label                = Iridium Simulator
Server Address              = localhost
Server Port                 = 9090
Debug Level                 = Debug

[Simulators.GPS]
Initial Position            = 41.13960451, -8.73837402

[Transports.CommManager]
Iridium Reports Period      = 3

[Transports.UDP]
Underwater Communications   = true
Always Transmitted Messages = SimulatedState
Transports                  = AnnounceService,
                              EntityList, EntityParameters, 
                            ;   EntityState, 
                              EstimatedState, EulerAngles,
                              FollowRefState,
                              GpsFix,
                              Heartbeat,
                              PathControlState, 
                              PlanControl, PlanControlState, PlanDB,
                              SoiCommand, SoiState,
                              SimulatedState,
                              VehicleState,
                              StateReport,
                              VerticalProfile

Rate Limiters               = AnnounceService:0.005,
                              EstimatedState:0.01,
                              EulerAngles:0.005,
                            ;   EntityState:0.005,
                              GpsFix:0.01,
                              Heartbeat:0.005,
                              SimulatedState:0.01,
                              StateReport:0.01,
                              PlanControlState:0.01,
                              PathControlState:0.01,
                              VehicleState:0.01

; Print Outgoing Messages     = 1

[Transports.Iridium]
Enabled                     = Never
